fix(ops): quoting serde_v8::Value (#19593)
The following code:

```rust
use deno_core::op;

#[op]
fn ops_serde_v8(value: serde_v8::Value) {
    //
}

fn main() {
    //
}
```

...with the following `Cargo.toml`:

```toml
[package]
name = "playground"
version = "0.1.0"
edition = "2021"

[dependencies]
deno_core = "0.191.0"
serde_v8 = "0.102.0"
```

...will not compile with the error:

```
error[E0433]: failed to resolve: use of undeclared crate or module `v8`
 --> src/main.rs:3:1
  |
3 | #[op]
  | ^^^^^ use of undeclared crate or module `v8`
  |
  = note: this error originates in the attribute macro `op` (in Nightly builds, run with -Z macro-backtrace for more info)
```

This PR is fixing the above issue by properly quoting
`deno_core::v8::Value` instead of `v8::Value`.